import type { MeritData, MeritType } from './catalog.js';

type MeritExamples = { [T in MeritType]: MeritData<T> };

/** Un mérito válido de cada tipo. Sirve de ejemplo en pruebas y en las vistas previas. */
export const MERIT_EXAMPLES: MeritExamples = {
  academic_record: {
    degree: 'Grado en Ingeniería Informática en Ingeniería del Software',
    honors: 3,
    outstanding: 12,
    notable: 20,
    pass: 5,
    averageGrade: 8.12,
    nationalAward: false,
    extraordinaryAward: true,
    tesina: false,
  },
  doctoral_studies: {
    qualifyingMaster: 'Máster Universitario en Ingeniería Informática',
    doctoralProgram: 'Programa de Doctorado en Tecnologías Informáticas',
    department: 'Ingeniería de Sistemas Informáticos y Telemáticos',
    courses: [
      { subject: 'Metodología de la investigación', credits: 6, grade: 'Sobresaliente' },
      { subject: 'Aprendizaje automático', credits: 4.5, grade: '9,2' },
    ],
    averageGrade: 9.1,
    masterExtraordinaryAward: false,
  },
  doctorate: {
    thesisTitle: 'Técnicas de optimización para la planificación de recursos en la nube',
    supervisors: 'Ana Pérez García; Luis Martín Sánchez',
    defenseDate: '2024-06-14',
    grade: 'Sobresaliente cum laude',
    extraordinaryAward: true,
    awardDate: '2025-03-10',
    international: true,
  },
  master: { name: 'Máster Universitario en Ciencia de Datos', credits: 60 },
  teacher_training: { credits: 15 },
  other_degree: {
    degree: 'Grado en Matemáticas',
    honors: null,
    outstanding: 4,
    notable: 18,
    pass: 10,
    averageGrade: 7.05,
  },
  language: { language: 'Inglés', level: 'C1', certifier: 'Cambridge Assessment English' },
  grant: {
    kind: 'fpu_fpi',
    name: 'Contrato predoctoral FPU',
    organization: 'Ministerio de Universidades',
    startDate: '2020-10-01',
    endDate: '2024-09-30',
    months: 48,
  },
  research_stay: {
    center: 'Technische Universität München',
    city: 'Múnich',
    country: 'Alemania',
    year: 2023,
    months: 3,
  },
  book: {
    title: 'Introducción a la computación en la nube',
    authors: 'Ruiz, I.; Pérez, A.',
    pages: 240,
    publisher: 'Servicio de Publicaciones de la UEx',
    cityCountry: 'Cáceres/España',
    year: 2022,
    isbn: '978-84-9127-000-7',
    legalDeposit: 'CC-123-2022',
  },
  book_chapter: {
    chapterTitle: 'Planificación de tareas con restricciones energéticas',
    authors: 'Ruiz, I.',
    firstPage: '45',
    lastPage: '68',
    bookTitle: 'Avances en sistemas distribuidos',
    pages: 320,
    publisher: 'Springer',
    cityCountry: 'Cham/Suiza',
    year: 2023,
    isbn: '9783031000007',
    legalDeposit: null,
  },
  article: {
    title: 'Energy-aware scheduling in heterogeneous clouds',
    authors: 'Ruiz, I.; Martín, L.; Pérez, A.',
    journal: 'Future Generation Computer Systems',
    volume: '152',
    firstPage: '101',
    lastPage: '115',
    year: 2024,
    doi: '10.1016/j.future.2024.01.001',
    indexed: true,
    index: 'JCR',
    otherIndex: null,
    quartile: 'Q1',
    category: 'Computer Science, Theory & Methods',
    rank: 12,
    categoryTotal: 143,
  },
  conference_talk: {
    authors: 'Ruiz, I.; Pérez, A.',
    title: 'Planificación consciente de la energía',
    congress: 'Jornadas de Paralelismo',
    scope: 'national',
    city: 'Cáceres',
    country: 'España',
    year: 2022,
  },
  poster: {
    authors: 'Ruiz, I.',
    title: 'A benchmark for serverless schedulers',
    congress: 'IEEE International Conference on Cloud Computing',
    scope: 'international',
    city: 'Chicago',
    country: 'Estados Unidos',
    year: 2023,
  },
  project: {
    title: 'Computación sostenible en el continuo nube-borde',
    scope: 'national',
    funder: 'Agencia Estatal de Investigación',
    code: 'PID2021-000000OB-I00',
    startDate: '2022-09-01',
    endDate: '2025-08-31',
    researchers: 8,
    principalInvestigator: 'Ana Pérez García',
  },
  thesis_supervision: {
    workTitle: 'Aprendizaje federado en dispositivos de borde',
    thesis: 'Defendida, Sobresaliente cum laude',
    defenseDate: '2026-02-20',
    doctoralStudent: 'Marta López Díaz',
  },
  art_exhibition: {
    authors: 'Ruiz, I.',
    title: 'Paisajes generativos',
    participation: 'collective',
    venue: 'Sala de exposiciones El Brocense',
    city: 'Cáceres',
    country: 'España',
    year: 2021,
  },
  industry_contract: {
    title: 'Optimización del despliegue de microservicios',
    scope: 'regional',
    funder: 'Empresa Tecnológica de Extremadura, S.L.',
    code: '123/2023',
    startDate: '2023-01-15',
    endDate: '2023-12-31',
    researchers: 3,
    principalInvestigator: 'Luis Martín Sánchez',
  },
  patent: {
    inventors: 'Ruiz, I.; Martín, L.',
    title: 'Sistema de planificación energética de centros de datos',
    applicationNumber: 'P202330001',
    date: '2023-05-04',
    holder: 'Universidad de Extremadura',
    companies: 'Datacenter Verde, S.A.',
  },
  peer_review: { journal: 'Journal of Parallel and Distributed Computing', rank: 'Q2' },
  professional_activity: {
    activity: 'Desarrollador de software',
    startDate: '2018-07-01',
    endDate: '2020-06-30',
    months: 24,
  },
};
